name=input("Enter your name :")
age=input("Enter your age :")
phone=input("Enter your phone number :")
print("Student Information")
print("--------------------")
print("Name :"+name)
print("Age :"+age)
print("Phone :"+phone)